
service: pdfer
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name



provider:
  name: aws
  ecr:
    images:
      pdfer-image:
        path: ./
  iamRoleStatements:
      - Effect: Allow
        Action:
          - "s3:GetObject"
          - "s3:ListBucket"
          - "s3:HeadObject"
          - "s3:PutObject"
          - "s3:PutObjectAcl"
        Resource: arn:aws:s3:::basementremodeling-archive-12345/*  

stage: v1
region: us-east-1


functions:
  generateProposal:
    image: 
      name: pdfer-image
    timeout: 200
    events:
      - httpApi:
          path: /
          method: post


